apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "jrcluster"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "jrcluster"
    spec:
      containers:
        - name: "jrcluster"
          image: "jrcontainerreg.azurecr.io/jrcluster"
          ports:
          - containerPort: 80