on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n jrcontainerReg -g jrcontainerReg8bbe-rg --location "West Europe" --sku Basic --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n jrcontainerReg --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n jrcontainerReg --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n jrcontainerReg --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: jrcontainerreg.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/azure-vote" -f  "azure-vote/Dockerfile" -t jrcontainerreg.azurecr.io/jrcluster:${{ github.sha }}
        docker push jrcontainerreg.azurecr.io/jrcluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_jrcluster_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep jrclusteracc5 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace jrclusteracc5`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: jrclusteracc5
        container-registry-url: jrcontainerreg.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: jrclusterdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: jrclusteracc5
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          jrcontainerreg.azurecr.io/jrcluster:${{ github.sha }}
        imagepullsecrets: |
          jrclusterdockerauth